// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

/**
 * @title AuthAiRegistry
 * @dev Immutable Registry for AuthAI Verification Certificates
 * This contract anchors forensic analysis verdicts to the Polygon Blockchain.
 */
contract AuthAiRegistry {
    address public owner;

    struct Certificate {
        string contentHash;
        string verdict;
        uint256 timestamp;
        bool exists;
    }

    // Mapping from Certificate ID (e.g., "AUTH-X92") to Certificate Data
    mapping(string => Certificate) public certificates;

    event CertificateMinted(string indexed certId, string contentHash, string verdict, uint256 timestamp);

    modifier onlyOwner() {
        require(msg.sender == owner, "Caller is not the owner");
        _;
    }

    constructor() {
        owner = msg.sender;
    }

    /**
     * @dev Mints a new certification record.
     * @param _certId The unique certificate ID generated by AuthAI.
     * @param _contentHash The SHA-256 hash of the analyzed content.
     * @param _verdict The forensic verdict (e.g., "HUMAN", "AI_GENERATED").
     */
    function mint(string memory _certId, string memory _contentHash, string memory _verdict) public onlyOwner {
        require(!certificates[_certId].exists, "Certificate ID already exists");

        certificates[_certId] = Certificate({
            contentHash: _contentHash,
            verdict: _verdict,
            timestamp: block.timestamp,
            exists: true
        });

        emit CertificateMinted(_certId, _contentHash, _verdict, block.timestamp);
    }

    /**
     * @dev Verifies if a certificate exists and matches the hash.
     * @param _certId The certificate ID to query.
     */
    function verify(string memory _certId) public view returns (string memory, string memory, uint256) {
        require(certificates[_certId].exists, "Certificate does not exist");
        Certificate memory cert = certificates[_certId];
        return (cert.contentHash, cert.verdict, cert.timestamp);
    }
}
